/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/state-tunnel';


export namespace Components {

  interface BaEngine {
    'canvas': HTMLCanvasElement;
  }
  interface BaEngineAttributes extends StencilHTMLAttributes {
    'canvas'?: HTMLCanvasElement;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BaEngine': Components.BaEngine;
  }

  interface StencilIntrinsicElements {
    'ba-engine': Components.BaEngineAttributes;
  }


  interface HTMLBaEngineElement extends Components.BaEngine, HTMLStencilElement {}
  var HTMLBaEngineElement: {
    prototype: HTMLBaEngineElement;
    new (): HTMLBaEngineElement;
  };

  interface HTMLElementTagNameMap {
    'ba-engine': HTMLBaEngineElement
  }

  interface ElementTagNameMap {
    'ba-engine': HTMLBaEngineElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
