// this file was auto-generated

import './components/BaAction'
import './components/BaActionEvent'
import './components/BaActionManager'
import './components/BaAnaglyphArcRotateCamera'
import './components/BaAnaglyphFreeCamera'
import './components/BaAnaglyphGamepadCamera'
import './components/BaAnaglyphUniversalCamera'
import './components/BaArcFollowCamera'
import './components/BaArcRotateCamera'
import './components/BaBackgroundMaterial'
import './components/BaBaseTexture'
import './components/BaCreateBox'
import './components/BaCamera'
import './components/BaColorGradingTexture'
import './components/BaCubeTexture'
import './components/BaCubeTextureAssetTask'
import './components/BaCustomProceduralTexture'
import './components/BaCreateCylinder'
import './components/BaCreateDashedLines'
import './components/BaCreateDecal'
import './components/BaDepthTextureCreationOptions'
import './components/BaDeviceOrientationCamera'
import './components/BaDirectionalLight'
import './components/BaCreateDisc'
import './components/BaDummyInternalTextureTracker'
import './components/BaDynamicTexture'
import './components/BaEngine'
import './components/BaFollowCamera'
import './components/BaFreeCamera'
import './components/BaGamepadCamera'
import './components/BaCreateGround'
import './components/BaCreateGroundFromHeightMap'
import './components/BaHDRCubeTexture'
import './components/BaHDRCubeTextureAssetTask'
import './components/BaHemisphericLight'
import './components/BaCreateIcoSphere'
import './components/BaInternalTexture'
import './components/BaKhronosTextureContainer'
import './components/BaCreateLathe'
import './components/BaLight'
import './components/BaCreateLineSystem'
import './components/BaCreateLines'
import './components/BaMaterial'
import './components/BaMaterialHelper'
import './components/BaMirrorTexture'
import './components/BaMultiMaterial'
import './components/BaNoiseProceduralTexture'
import './components/BaPBRBaseMaterial'
import './components/BaPBRBaseSimpleMaterial'
import './components/BaPBRMaterial'
import './components/BaPBRMetallicRoughnessMaterial'
import './components/BaPBRSpecularGlossinessMaterial'
import './components/BaCreatePlane'
import './components/BaPointLight'
import './components/BaCreatePolygon'
import './components/BaCreatePolyhedron'
import './components/BaPositionNormalTextureVertex'
import './components/BaProceduralTexture'
import './components/BaProceduralTextureSceneComponent'
import './components/BaPushMaterial'
import './components/BaRawCubeTexture'
import './components/BaRawTexture'
import './components/BaRawTexture3D'
import './components/BaRefractionTexture'
import './components/BaRenderTargetTexture'
import './components/BaCreateRibbon'
import './components/BaScene'
import './components/BaShaderMaterial'
import './components/BaShadowLight'
import './components/BaCreateSphere'
import './components/BaSpotLight'
import './components/BaSprite'
import './components/BaSpriteManager'
import './components/BaSpriteSceneComponent'
import './components/BaStandardMaterial'
import './components/BaStereoscopicArcRotateCamera'
import './components/BaStereoscopicFreeCamera'
import './components/BaStereoscopicGamepadCamera'
import './components/BaStereoscopicUniversalCamera'
import './components/BaTargetCamera'
import './components/BaTexture'
import './components/BaTextureAssetTask'
import './components/BaTextureOptimization'
import './components/BaCreateTiledGround'
import './components/BaCreateTorus'
import './components/BaCreateTorusKnot'
import './components/BaTouchCamera'
import './components/BaCreateTube'
import './components/BaUniversalCamera'
import './components/BaVRCameraMetrics'
import './components/BaVRDeviceOrientationArcRotateCamera'
import './components/BaVRDeviceOrientationFreeCamera'
import './components/BaVRDeviceOrientationGamepadCamera'
import './components/BaVideoTexture'
import './components/BaVirtualJoysticksCamera'
import './components/BaVolumetricLightScatteringPostProcess'
import './components/BaWebVRFreeCamera'

export const Action = 'ba-action'
export const ActionEvent = 'ba-action-event'
export const ActionManager = 'ba-action-manager'
export const AnaglyphArcRotateCamera = 'ba-anaglyph-arc-rotate-camera'
export const AnaglyphFreeCamera = 'ba-anaglyph-free-camera'
export const AnaglyphGamepadCamera = 'ba-anaglyph-gamepad-camera'
export const AnaglyphUniversalCamera = 'ba-anaglyph-universal-camera'
export const ArcFollowCamera = 'ba-arc-follow-camera'
export const ArcRotateCamera = 'ba-arc-rotate-camera'
export const BackgroundMaterial = 'ba-background-material'
export const BaseTexture = 'ba-base-texture'
export const CreateBox = 'ba-create-box'
export const Camera = 'ba-camera'
export const ColorGradingTexture = 'ba-color-grading-texture'
export const CubeTexture = 'ba-cube-texture'
export const CubeTextureAssetTask = 'ba-cube-texture-asset-task'
export const CustomProceduralTexture = 'ba-custom-procedural-texture'
export const CreateCylinder = 'ba-create-cylinder'
export const CreateDashedLines = 'ba-create-dashed-lines'
export const CreateDecal = 'ba-create-decal'
export const DepthTextureCreationOptions = 'ba-depth-texture-creation-options'
export const DeviceOrientationCamera = 'ba-device-orientation-camera'
export const DirectionalLight = 'ba-directional-light'
export const CreateDisc = 'ba-create-disc'
export const DummyInternalTextureTracker = 'ba-dummy-internal-texture-tracker'
export const DynamicTexture = 'ba-dynamic-texture'
export const Engine = 'ba-engine'
export const FollowCamera = 'ba-follow-camera'
export const FreeCamera = 'ba-free-camera'
export const GamepadCamera = 'ba-gamepad-camera'
export const CreateGround = 'ba-create-ground'
export const CreateGroundFromHeightMap = 'ba-create-ground-from-height-map'
export const HDRCubeTexture = 'ba-hdr-cube-texture'
export const HDRCubeTextureAssetTask = 'ba-hdr-cube-texture-asset-task'
export const HemisphericLight = 'ba-hemispheric-light'
export const CreateIcoSphere = 'ba-create-ico-sphere'
export const InternalTexture = 'ba-internal-texture'
export const KhronosTextureContainer = 'ba-khronos-texture-container'
export const CreateLathe = 'ba-create-lathe'
export const Light = 'ba-light'
export const CreateLineSystem = 'ba-create-line-system'
export const CreateLines = 'ba-create-lines'
export const Material = 'ba-material'
export const MaterialHelper = 'ba-material-helper'
export const MirrorTexture = 'ba-mirror-texture'
export const MultiMaterial = 'ba-multi-material'
export const NoiseProceduralTexture = 'ba-noise-procedural-texture'
export const PBRBaseMaterial = 'ba-pbr-base-material'
export const PBRBaseSimpleMaterial = 'ba-pbr-base-simple-material'
export const PBRMaterial = 'ba-pbr-material'
export const PBRMetallicRoughnessMaterial = 'ba-pbr-metallic-roughness-material'
export const PBRSpecularGlossinessMaterial = 'ba-pbr-specular-glossiness-material'
export const CreatePlane = 'ba-create-plane'
export const PointLight = 'ba-point-light'
export const CreatePolygon = 'ba-create-polygon'
export const CreatePolyhedron = 'ba-create-polyhedron'
export const PositionNormalTextureVertex = 'ba-position-normal-texture-vertex'
export const ProceduralTexture = 'ba-procedural-texture'
export const ProceduralTextureSceneComponent = 'ba-procedural-texture-scene-component'
export const PushMaterial = 'ba-push-material'
export const RawCubeTexture = 'ba-raw-cube-texture'
export const RawTexture = 'ba-raw-texture'
export const RawTexture3D = 'ba-raw-texture3-d'
export const RefractionTexture = 'ba-refraction-texture'
export const RenderTargetTexture = 'ba-render-target-texture'
export const CreateRibbon = 'ba-create-ribbon'
export const Scene = 'ba-scene'
export const ShaderMaterial = 'ba-shader-material'
export const ShadowLight = 'ba-shadow-light'
export const CreateSphere = 'ba-create-sphere'
export const SpotLight = 'ba-spot-light'
export const Sprite = 'ba-sprite'
export const SpriteManager = 'ba-sprite-manager'
export const SpriteSceneComponent = 'ba-sprite-scene-component'
export const StandardMaterial = 'ba-standard-material'
export const StereoscopicArcRotateCamera = 'ba-stereoscopic-arc-rotate-camera'
export const StereoscopicFreeCamera = 'ba-stereoscopic-free-camera'
export const StereoscopicGamepadCamera = 'ba-stereoscopic-gamepad-camera'
export const StereoscopicUniversalCamera = 'ba-stereoscopic-universal-camera'
export const TargetCamera = 'ba-target-camera'
export const Texture = 'ba-texture'
export const TextureAssetTask = 'ba-texture-asset-task'
export const TextureOptimization = 'ba-texture-optimization'
export const CreateTiledGround = 'ba-create-tiled-ground'
export const CreateTorus = 'ba-create-torus'
export const CreateTorusKnot = 'ba-create-torus-knot'
export const TouchCamera = 'ba-touch-camera'
export const CreateTube = 'ba-create-tube'
export const UniversalCamera = 'ba-universal-camera'
export const VRCameraMetrics = 'ba-vr-camera-metrics'
export const VRDeviceOrientationArcRotateCamera = 'ba-vr-device-orientation-arc-rotate-camera'
export const VRDeviceOrientationFreeCamera = 'ba-vr-device-orientation-free-camera'
export const VRDeviceOrientationGamepadCamera = 'ba-vr-device-orientation-gamepad-camera'
export const VideoTexture = 'ba-video-texture'
export const VirtualJoysticksCamera = 'ba-virtual-joysticks-camera'
export const VolumetricLightScatteringPostProcess = 'ba-volumetric-light-scattering-post-process'
export const WebVRFreeCamera = 'ba-web-vr-free-camera'
